const questions = [
  // --- 1-15: Signs & Notices (ป้ายและประกาศ) ---
  { "id": 1, "category": "English Reading", "question": "A sign says: 'NO SMOKING'. What does it mean?", "options": ["You can smoke here", "You must not smoke here", "Smoking is allowed", "You can buy cigarettes here"], "answerIndex": 1 },
  { "id": 2, "category": "English Reading", "question": "A sign says: 'WET FLOOR'. What should you do?", "options": ["Run quickly", "Be careful", "Jump over it", "Sit down"], "answerIndex": 1 },
  { "id": 3, "category": "English Reading", "question": "At the library: 'SILENCE PLEASE'. What does it mean?", "options": ["You can talk loudly", "You should be quiet", "You can play music", "You must sing"], "answerIndex": 1 },
  { "id": 4, "category": "English Reading", "question": "A sign says: 'STAFF ONLY'. Who can enter?", "options": ["Customers", "Students", "Employees", "Everyone"], "answerIndex": 2 },
  { "id": 5, "category": "English Reading", "question": "A sign says: 'KEEP OFF THE GRASS'. What does it mean?", "options": ["Don't walk on the grass", "Sit on the grass", "Water the grass", "Cut the grass"], "answerIndex": 0 },
  { "id": 6, "category": "English Reading", "question": "On a door: 'PUSH'. What should you do?", "options": ["Pull the door", "Kick the door", "Press the door forward", "Wait for someone"], "answerIndex": 2 },
  { "id": 7, "category": "English Reading", "question": "At a shop: 'BUY 1 GET 1 FREE'. If you buy 2 shirts, how many do you get?", "options": ["2", "3", "4", "5"], "answerIndex": 2 },
  { "id": 8, "category": "English Reading", "question": "A sign says: 'OUT OF ORDER'. What does it mean?", "options": ["It is working well", "It is broken", "It is new", "It is expensive"], "answerIndex": 1 },
  { "id": 9, "category": "English Reading", "question": "A sign says: 'DANGER'. What does it mean?", "options": ["It is safe", "It is not safe", "It is fun", "It is beautiful"], "answerIndex": 1 },
  { "id": 10, "category": "English Reading", "question": "At the airport: 'DEPARTURES'. Where are you going?", "options": ["Coming home", "Leaving to another place", "Waiting for bags", "Buying tickets"], "answerIndex": 1 },
  { "id": 11, "category": "English Reading", "question": "A sign says: 'EXIT'. What is it for?", "options": ["Going in", "Going out", "Sitting", "Eating"], "answerIndex": 1 },
  { "id": 12, "category": "English Reading", "question": "On a medicine bottle: 'SHAKE WELL BEFORE USE'. What should you do?", "options": ["Drink it fast", "Shake the bottle", "Keep it in the fridge", "Throw it away"], "answerIndex": 1 },
  { "id": 13, "category": "English Reading", "question": "A sign says: 'FRAGILE'. What is inside?", "options": ["Something strong", "Something that breaks easily", "Something heavy", "Something cheap"], "answerIndex": 1 },
  { "id": 14, "category": "English Reading", "question": "At a parking lot: 'RESERVED'. Can you park there?", "options": ["Yes, anytime", "No, it is kept for someone", "Yes, if it's free", "Only on weekends"], "answerIndex": 1 },
  { "id": 15, "category": "English Reading", "question": "A sign says: 'DO NOT DISTURB'. Where would you see this?", "options": ["On a hotel door", "In a park", "At a market", "On a bus"], "answerIndex": 0 },

  // --- 16-30: Advertisements & Labels (โฆษณาและฉลาก) ---
  { "id": 16, "category": "English Reading", "question": "Ad: '50% OFF ALL ITEMS'. How much do you pay?", "options": ["Full price", "Half price", "Double price", "Nothing"], "answerIndex": 1 },
  { "id": 17, "category": "English Reading", "question": "Label: 'Best Before 20/12/2026'. When should you eat it?", "options": ["After that date", "Before that date", "Anytime", "Never"], "answerIndex": 1 },
  { "id": 18, "category": "English Reading", "question": "Ad: 'FREE DELIVERY'. What is free?", "options": ["The food", "The shipping", "The box", "The drink"], "answerIndex": 1 },
  { "id": 19, "category": "English Reading", "question": "Label: '100% Cotton'. What is the shirt made of?", "options": ["Silk", "Plastic", "Natural cotton", "Wool"], "answerIndex": 2 },
  { "id": 20, "category": "English Reading", "question": "Ad: 'Open Daily'. When can you go there?", "options": ["Every day", "Only weekdays", "Only weekends", "Once a month"], "answerIndex": 0 },
  { "id": 21, "category": "English Reading", "question": "Ad: 'Hiring Now'. What does the company want?", "options": ["Customers", "Workers", "Money", "Orders"], "answerIndex": 1 },
  { "id": 22, "category": "English Reading", "question": "Label: 'Hand Wash Only'. Can you use a machine?", "options": ["Yes", "No", "Sometimes", "Maybe"], "answerIndex": 1 },
  { "id": 23, "category": "English Reading", "question": "Ad: 'Limited Time Offer'. What does it mean?", "options": ["Available forever", "Available for a short time", "No more items", "Very expensive"], "answerIndex": 1 },
  { "id": 24, "category": "English Reading", "question": "Ad: 'Contact us for more details'. What should you do?", "options": ["Buy it", "Ask for more information", "Wait", "Go there"], "answerIndex": 1 },
  { "id": 25, "category": "English Reading", "question": "Label: 'Flammable'. What is the danger?", "options": ["It can break", "It can catch fire", "It is poisonous", "It is heavy"], "answerIndex": 1 },
  { "id": 26, "category": "English Reading", "question": "Ad: 'Under New Management'. What changed?", "options": ["The building", "The owners/bosses", "The price", "The location"], "answerIndex": 1 },
  { "id": 27, "category": "English Reading", "question": "Label: 'Keep out of reach of children'. Where should you put it?", "options": ["On the floor", "In a high place", "In a toy box", "Under the bed"], "answerIndex": 1 },
  { "id": 28, "category": "English Reading", "question": "Ad: 'Rent: 5,000 Baht/month'. What is this for?", "options": ["A house/room", "A car", "A job", "A meal"], "answerIndex": 0 },
  { "id": 29, "category": "English Reading", "question": "Ad: 'Sold Out'. Can you buy it now?", "options": ["Yes", "No", "Maybe", "Next week"], "answerIndex": 1 },
  { "id": 30, "category": "English Reading", "question": "Label: 'Made in Thailand'. Where was it produced?", "options": ["Japan", "China", "Thailand", "USA"], "answerIndex": 2 },

  // --- 31-40: Emails & Letters (อีเมลและจดหมาย) ---
  { "id": 31, "category": "English Reading", "question": "In an email: 'Dear Mr. Brown'. Who is the receiver?", "options": ["Mr. Brown", "The writer", "The company", "No one"], "answerIndex": 0 },
  { "id": 32, "category": "English Reading", "question": "In an email: 'Best regards'. Where is this part?", "options": ["Beginning", "Middle", "End", "Subject"], "answerIndex": 2 },
  { "id": 33, "category": "English Reading", "question": "Subject: 'Meeting Postponed'. When is the meeting?", "options": ["At the same time", "Earlier", "Later/Delayed", "Cancelled"], "answerIndex": 2 },
  { "id": 34, "category": "English Reading", "question": "Email: 'Please find attached the report'. What is in the email?", "options": ["A photo", "A file/document", "A link", "A video"], "answerIndex": 1 },
  { "id": 35, "category": "English Reading", "question": "Email: 'I look forward to seeing you'. What does the writer feel?", "options": ["Excited/Happy to meet", "Sad to meet", "Angry", "Bored"], "answerIndex": 0 },
  { "id": 36, "category": "English Reading", "question": "Email: 'RSVP by Friday'. What should you do?", "options": ["Go on Friday", "Reply by Friday", "Wait until Friday", "Pay on Friday"], "answerIndex": 1 },
  { "id": 37, "category": "English Reading", "question": "In a letter: 'To whom it may concern'. When do you use this?", "options": ["Writing to a friend", "Writing to someone you don't know the name", "Writing to your boss", "Writing to family"], "answerIndex": 1 },
  { "id": 38, "category": "English Reading", "question": "Email: 'Urgent: Action required'. What should the reader do?", "options": ["Wait a few days", "Do something quickly", "Ignore it", "Delete it"], "answerIndex": 1 },
  { "id": 39, "category": "English Reading", "question": "Letter: 'We regret to inform you...'. What kind of news follows?", "options": ["Good news", "Bad news", "Funny news", "No news"], "answerIndex": 1 },
  { "id": 40, "category": "English Reading", "question": "Email: 'Thank you for your cooperation'. What is the writer doing?", "options": ["Complaining", "Asking for money", "Expressing thanks", "Saying hello"], "answerIndex": 2 },

  // --- 41-50: Short Passages (บทความสั้น) ---
  { "id": 41, "category": "English Reading", "question": "Passage: 'Tom is a police officer. He works at the station.' What is Tom's job?", "options": ["Doctor", "Police officer", "Teacher", "Driver"], "answerIndex": 1 },
  { "id": 42, "category": "English Reading", "question": "Passage: 'The sun rises in the east.' Where does the sun rise?", "options": ["West", "North", "East", "South"], "answerIndex": 2 },
  { "id": 43, "category": "English Reading", "question": "Passage: 'Yesterday was rainy, but today is sunny.' How is the weather today?", "options": ["Rainy", "Cloudy", "Sunny", "Cold"], "answerIndex": 2 },
  { "id": 44, "category": "English Reading", "question": "Passage: 'Anna has two dogs and one cat.' How many pets does she have?", "options": ["1", "2", "3", "4"], "answerIndex": 2 },
  { "id": 45, "category": "English Reading", "question": "Passage: 'Football is popular in Thailand.' What is popular?", "options": ["Basketball", "Football", "Tennis", "Golf"], "answerIndex": 1 },
  { "id": 46, "category": "English Reading", "question": "Passage: 'He was born in 1990.' How old was he in 2000?", "options": ["5", "10", "15", "20"], "answerIndex": 1 },
  { "id": 47, "category": "English Reading", "question": "Passage: 'Drink 8 glasses of water a day for good health.' Why should you drink water?", "options": ["To be sick", "To be healthy", "To be rich", "To be fast"], "answerIndex": 1 },
  { "id": 48, "category": "English Reading", "question": "Passage: 'Bangkok is the capital of Thailand.' What is Bangkok?", "options": ["A country", "A city/capital", "A park", "A river"], "answerIndex": 1 },
  { "id": 49, "category": "English Reading", "question": "Passage: 'The car hit the tree because the driver was sleepy.' Why did the accident happen?", "options": ["Bad road", "Sleepy driver", "Strong wind", "Rain"], "answerIndex": 1 },
  { "id": 50, "category": "English Reading", "question": "Passage: 'Exercise is good for everyone.' Who should exercise?", "options": ["Only kids", "Only old people", "Everyone", "No one"], "answerIndex": 2 }
];
